spring.application.name=bookshelf
spring.datasource.url=jdbc:postgresql://ep-flat-glitter-aql3bzot-pooler.c-8.us-east-1.aws.neon.tech/neondb?
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YV2Wvmp3Msbq

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080